### ISSUE TITLE
[Bug] Updating KCTG-2e on foundry generates validation error "id: may not be undefined"

### ISSUE THREAD

**Issue by maplealmond** [kristkos/KCTG-2e#1]
When updating the module version 1.1.1b from Foundry, Foundry will throw an error saying that there is a module validation error.

The module id clearly exists, but this error happens multiple times per update so I believe it may be the id of something within the compendium.

Reproduction should be as strait-forward as installing the module on a clean version of foundry (which succeeds) and then trying to update it (which throws errors)

**Comment by kristkos** [comment]
> When updating the module version 1.1.1b from Foundry, Foundry will throw an error saying that there is a module validation error.
> 
> The module id clearly exists, but this error happens multiple times per update so I believe it may be the id of something within the compendium.
> 
> Reproduction should be as strait-forward as installing the module on a clean version of foundry (which succeeds) and then trying to update it (which throws errors)

I was able to fix it. Thank you so much for the heads up.

**Comment by maplealmond** [comment]
I wasn't able to fix by updating in place, but an uninstall/reinstall seems to have solved it.  Confirming the error is gone.

**Comment by kristkos** [comment]
I think I also fixed 1.1.1b also. 
Thank you so much yet again!
