### ISSUE TITLE
Error Updating

### ISSUE THREAD

**Issue by Strangley-Browne** [kristkos/KCTG-2e#2]
When checked for update this error appears
![image](https://github.com/kristkos/KCTG-2e/assets/87890230/4ea5ed2b-c08e-4a22-9e4e-ff82d71edf89)

**Comment by kristkos** [comment]
Hello Strangley,

Thank you for the comment, this has been already fixed. 
Please update to 1.1.3 by uninstalling and reinstalling, do let me know if it does persist after.

Thank you,
Kris

**Comment by Strangley-Browne** [comment]
Thats was it all good now!

**Comment by Strangley-Browne** [comment]
All good now. That was it
