### ISSUE TITLE
Request: Item List in a Markdown Table

### ISSUE THREAD

**Issue by GeorgeWL** [kristkos/KCTG-2e#3]
Just so it's easier to know what's here before installing it

**Comment by kristkos** [comment]
I was thinking to add one, however, all of the items were posted in multiple places already. 
https://www.patreon.com/posts/2024-new-master-76424106
https://github.com/kristkos/KCTG-2e/tree/main/images - This is technically that without the description.

**Comment by GeorgeWL** [comment]
mayube just linking back to those in the readme and/or package description might make sense then? I didn't know these pages existed until you linked 🙂

**Comment by kristkos** [comment]
Will do, by EOD, actually that is a great idea. Thank you.
