### ISSUE TITLE
[Suggestion] More Food

### ISSUE THREAD

**Issue by Peach774** [kristkos/KCTG-2e#4]
The default foundry icons and the KCTG icons are severely lacking in food. For example, there are no sandwiches, which are perhaps the most universal food item.

**Comment by kristkos** [comment]
"It is rumored that the knowledge of making sandwiches has faded over time, but I believe I have the notes from an old weary traveler on how to prepare one."

A minimum of 1 sammich will be incoming with the next pack

**Comment by kristkos** [comment]
> The default foundry icons and the KCTG icons are severely lacking in food. For example, there are no sandwiches, which are perhaps the most universal food item.

By Tuesday I should have a new pack out. To avoid repetition, I added 1 sandwich, with two additional icons for alternatives within the files.
