### ISSUE TITLE
Foundry says 1.8.0 is 1.7.0 and continually updates

### ISSUE THREAD

**Issue by Peach774** [kristkos/KCTG-2e#5]
I think you mightve forgotten to change the version in the manifest.json

**Comment by kristkos** [comment]
Just realized I've uploaded the wrong zip. Thank you. Should be fixed now. Let me know if it works.

**Comment by Peach774** [comment]
> Just realized I've uploaded the wrong zip. Thank you. Should be fixed now. Let me know if it works.

Looks like it is fixed!
