### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by Lioheart** [kristkos/KCTG-2e#7]
Hi,

Brined Cheese and Butter has the same description.
Seed Potato and Sextant has the same description.

**Comment by kristkos** [comment]
Fix should be up in like 5min

**Comment by Lioheart** [comment]
I check everything you add as I translate your goods 😃 
For the moment, the rest is ok.

**Comment by kristkos** [comment]
Holy, let me know with any packs if you'll need the raw text.

**Comment by Lioheart** [comment]
At the moment I have everything translated.

I found a way to download raw text from the module pack.
